config/routes.rb
Rails.application.routes.draw do
  resources :rentals
  resources :movies
  resources :customers
  resources :login, only: [:new, :create]

  get "/login", to: 'login#new', as: "login"
  post "/login", to: 'login#create'

  delete "/logout", to: 'login#destroy'

  root "login#new"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_secure_password

  validates :name, presence: true
  validates :username, presence: true, uniqueness: true
  validates :password, presence: true

  has_many :rentals
  has_many :movies, through: :rentals
end

app/models/movie.rb
class Movie < ApplicationRecord
  validates :title, presence: true
  validates :overview, presence: true

  has_many :rentals
  has_many :customers, through: :rentals
end

app/models/rental.rb
class Rental < ApplicationRecord
  validates :rental_length, presence: true

  belongs_to :customer
  belongs_to :movie
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :setup_auth_variables

  def setup_auth_variables
    @customer_id = session[:customer_id]
    @logged_in = !!@customer_id
    if @logged_in
      @current_customer = Customer.find(@customer_id)
    end
  end

  def authorized
    if !@logged_in
      flash["message"] = "You must be logged in!"
      return redirect_to new_login_path
    end
  end

  def logout
    session[:customer_id] = nil
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :find_customer, only: [:show, :edit, :update, :destroy]
  before_action :authorized, only: [:index, :show, :edit, :update, :destroy]

  def index
    @customers = Customer.all
  end

  def show
  end

  def new
    @customer = Customer.new
  end

  def create
    @customer = Customer.create(customer_params)
    if @customer.valid?
      flash["message"] = "Successfully created an account!"
      redirect_to new_login_path
    else
      flash["message"] = "Unsuccessful, please try again."
      redirect_to new_customer_path
    end
  end

  def edit
  end

  def update
    if @customer.update(customer_params)
      redirect_to @customer
    else
      redirect_to edit_customer_path(@customer)
    end
  end

  def destroy
    @customer.destroy
    redirect_to new_login_path
  end

  private
  def customer_params
    params.require(:customer).permit(:name, :username, :password)
  end

  def find_customer
    @customer = Customer.find(params[:id])
  end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  def new
  end

  def create
    @customer = Customer.find_by(username: params[:username])
    if @customer && @customer.authenticate(params[:password])
      flash["message"] = "Successfully logged in #{@customer.name}!"
      session[:customer_id] = @customer.id
      redirect_to movies_path
    else
      flash["message"] = "Incorrect Username or Password"
      redirect_to new_login_path
    end
  end

  def destroy
    logout
    redirect_to new_login_path
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :find_movie, only: [:show, :edit, :update, :delete]

  def index
    @movies = Movie.all
  end

  def show
    cookies[:movie_id] = @movie.id
  end

  def new
    @movie = Movie.new
  end

  def create
    @movie = Movie.create(movie_params)
    redirect_to @movie
  end

  def edit
  end

  def update
    @movie.update(rental_params)
    redirect_to @movie
  end

  private

  def find_movie
    @movie = Movie.find(params[:id])
  end

  def movie_params
    params.require(:movie).permit(:title, :release_date, :genre, :overview, :poster_path, :rating)
  end

end

app/controllers/rentals_controller.rb
class RentalsController < ApplicationController
  before_action :find_rental, only: [:show, :edit, :update, :destroy]
  before_action :find_movie, only: [:new, :create]
  before_action :authorized

  def index
    @rentals = Rental.all
  end

  def show
  end

  def new
    @rental = Rental.new
  end

  def create
    @rental = Rental.create(rental_params)
    redirect_to @rental
  end

  def edit
  end

  def update
    @rental.update(rental_params)
    redirect_to @rental
  end

  def destroy
    @rental.destroy
    redirect_to rentals_path
  end

  private

  def find_rental
    @rental = Rental.find(params[:id])
  end

  def find_movie
    @movie = Movie.find(cookies[:movie_id])
  end

  def rental_params
    params.require(:rental).permit(:customer_id, :movie_id, :rental_length)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/rentals_helper.rb
module RentalsHelper
end

app/views/customers/edit.html.erb
<div class="row align-items-center justify-content-center" ">
<div class="col-5 black-bg">

<h1>Edit <%= @customer.name %></h1>

<%= form_for @customer do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, class: "form-control" %>
  <br>

  <%= f.label :username %>
  <%= f.text_field :username, class: "form-control" %>
  <br>

  <%= f.label :password %>
  <%= f.password_field :password, class: "form-control" %>
  <br>

  <%= f.submit class: "btn btn-danger float-right"%>
<% end %>
</div>
</div>

app/views/customers/index.html.erb
<div class="row align-items-center justify-content-center" ">
<div class="col-5 black-bg">

  <h1>All Customers</h1>
<ul>
  <% @customers.each do |customer| %>
    <li>
      <%= link_to customer.name, customer_path(customer) %>
    </li>
  <% end %>
</ul>
</div>
</div>

app/views/customers/new.html.erb
<div class="row align-items-center justify-content-center" ">
<div class="col-4 black-bg">

<h1>New Customer</h1>

<%= form_for @customer do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, class: "form-control" %>
  <br>

  <%= f.label :username %>
  <%= f.text_field :username, class: "form-control" %>
  <br>

  <%= f.label :password %>
  <%= f.password_field :password, class: "form-control" %>
  <br>

  <%= f.submit class: "btn btn-danger float-right" %>
<% end %>
</div>
</div>

app/views/customers/show.html.erb
<div class="row align-items-center justify-content-center" ">
<div class="col-6 black-bg">
  <h1><%= @customer.name %>'s Profile Page</h1>

  <hr>
<p><strong>E-mail: </strong><%= @customer.username %></p>

<% if @current_customer.id == @customer.id %>

  <p><strong>Rented Movies</strong></p>
  <ul>
    <% @customer.rentals.each do |rental| %>
      <li>
        <%= link_to "#{rental.movie.title}", rental_path(rental.id) %>
      </li>
    <% end %>
  </ul>

    <%= link_to "Edit Profile", edit_customer_path, class: "btn btn-danger float-right button-margin" %>
    <%= link_to "Delete Account", customer_path, class: "btn btn-danger float-right button-margin", method: :delete %>
  <%= link_to "Rent a Movie", movies_path, class: "btn btn-danger float-right button-margin" %>

<% else %>

  <p><strong>Rented Movies</strong></p>
  <ul>
    <% @customer.rentals.each do |rental| %>
      <li>
        <%= link_to "#{rental.movie.title}", rental_path(rental.id) %>
      </li>
    <% end %>
  </ul>

<% end %>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VHSClub</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'bootstrap', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
<!--  <div class="top-container">-->
    <div class="container">
    <navbar class="navbar navbar-dark fs-dark">
      <% if @logged_in %>
        <p>User: <span class="user"><%= @current_customer.name %></span>
        <%= link_to "Profile Page", customer_path(@current_customer) %>  |
        <%= link_to "All Customers", customers_path %>  |
        <%= link_to "All Movies", movies_path %>  |
        <%= link_to "All Rentals", rentals_path %>  |
        <%= link_to "Logout", "/logout", method: :delete %></p>
      <% else %>
        <p><%= link_to "Login", new_login_path %> |
        <%= link_to "Register", new_customer_path %></p>
      <% end %>

      <% if flash[:message] %>
        <p class="message">
          <%= flash[:message] %>
        </p>
      <% end %>
    </navbar>
    </div>
    <div class="container">


    <div class="container">

      <%= yield %>
    </div>
    </div>
<!--  </div>-->
  </body>
</html>

app/views/login/new.html.erb
<div id="logo">
  <img src="<%= asset_path "logo.png" %>" alt="Logo">
</div>



<div class="row align-items-center justify-content-center" ">
  <div class="col-4 black-bg">


<h1>Login</h1>

<%= form_tag "/login" do %>
  <%= label_tag :username %>
  <%= text_field_tag :username, nil, class: "form-control" %>
  <br>

  <%= label_tag :password %>
  <%= password_field_tag :password, nil, class: "form-control" %>
  <br>

  <%= submit_tag "Login", class: "btn btn-danger float-right" %>
<% end %>
  </div>
</div>

app/views/movies/edit.html.erb
<div class="row align-items-center justify-content-center" ">
<div class="col-5 black-bg">
<h1>Editing <%= @movie.title %></h1>
<p><%= link_to "Cancel", movie_path %> |
  <%= link_to "Delete this movie", movie_path, method: :delete %>
</p>

<%= form_for @movie do |f| %>
  <p>
    <%= f.label 'Title: ' %>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label 'Release Date: ' %>
    <%= f.text_field :release_date %>
  </p>

  <p>
    <%= f.label 'Genre: ' %>
    <%= f.text_field :genre %>
  </p>

  <p><%= f.submit %></p>

<% end %>
</div>

app/views/movies/index.html.erb
<h1>Showing list of available movies</h1>
<div class="grid-container">

<% @movies.each do |movie| %>
  <article id="3685" class="location-listing">

    <div class="movie-image">
      <a href="<%= movie_path(movie.id) %>">
        <img src="http://image.tmdb.org/t/p/w185/<%= movie.poster_path %>" alt="san francisco"></a>
      <a class="movie-title" href="#"><%= movie.title %></a>
    </div>

  </article>
  <% end %>
</div>

app/views/movies/new.html.erb
<div class="row align-items-center justify-content-center" ">
<div class="col-5 black-bg">
<h1>Adding New Movie</h1>

<%= form_for @movie do |f| %>
  <p>
    <%= f.label 'Title: ' %>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label 'Release Date: ' %>
    <%= f.text_field :release_date %>
  </p>

  <p>
    <%= f.label 'Genre: ' %>
    <%= f.text_field :genre %>
  </p>

  <p><%= f.submit %></p>

<% end %>
</div>
</div>

app/views/movies/show.html.erb
<div class="content position-relative">
  <h1>Movie Details</h1>
  <hr>
  <img class="thumb" src="http://image.tmdb.org/t/p/w185<%= @movie.poster_path %>" alt="<%= @movie.title %>">


<p><strong>Title: </strong><%= @movie.title %> <br />

<strong>Release Date: </strong><%= @movie.release_date %> <br />

<strong>Genre: </strong><%= @movie.genre %> <br />

<strong>Rating: </strong><%= @movie.rating %> <br />

  <strong>Overview: </strong><%= @movie.overview %></p>

  <p class="buttons">
    <%= link_to "Rent Movie", new_rental_path, class: "btn btn-danger float-right" %>
    <%= link_to "Return To Movies List", movies_path, class: "btn btn-danger float-right button-margin" %>
  </p>

</div>

app/views/rentals/edit.html.erb
<div class="row align-items-center justify-content-center" ">
<div class="col-5 black-bg">
  <h1>Editing Rental</h1>
  <hr>
<%= form_for @rental do |f| %>
  <p>
    Renter: <%= @current_customer.name %>
    <%= f.hidden_field :customer_id, value: @current_customer.id %>
  </p>

  <p>
    Movie: <%= @rental.movie.title %>
    <%= f.hidden_field :movie_id, value: @rental.movie.id %>
  </p>

  <p>
    <%= f.label :rental_length, "Rental Duration: " %>
    <%= f.number_field(:rental_length, in: 1..7) %> days
  </p>

    <%= f.submit "Edit Rental!", class: "btn btn-danger float-right button-margin" %>
    <%= link_to "Go Back", rental_path, class: "btn btn-danger float-right button-margin" %>
<% end %>
</div>
</div>

app/views/rentals/index.html.erb
<div class="row align-items-center justify-content-center" ">
<div class="col-7 black-bg">
<h1>List of All Rentals</h1>

<hr>

<ul>
  <% @rentals.each do |rental| %>
    <li> <a href="customers/<%= rental.customer_id %>"><%= rental.customer.name %></a> rented <a href="movies/<%= rental.movie_id %>"><%= rental.movie.title %></a> for <%= rental.rental_length %> days.</li>
  <% end %>
</ul>

  <p>
    <%= link_to "Rent a Movie", movies_path, class: "btn btn-danger float-right" %>
  </p>
</div>
</div>

app/views/rentals/new.html.erb
<div class="row align-items-center justify-content-center" ">
<div class="col-5 black-bg">
  <h1>Rent Movie</h1>
<%= form_for @rental do |f| %>

  <p>
    Renter: <%= @current_customer.name %>
    <%= f.hidden_field :customer_id, value: @current_customer.id %>
  </p>

  <p>
    Movie: <%= @movie.title %>
    <%= f.hidden_field :movie_id, value: @movie.id %>
  </p>

  <p>
    <%= f.label :rental_length, "Rental Duration: " %>
    <%= f.number_field(:rental_length, in: 1..7) %> days
  </p>

  <%= f.submit "Rent This Movie!", class: "btn btn-danger float-right" %>
<% end %>
</div>
</div>

app/views/rentals/show.html.erb
<div class="row align-items-center justify-content-center" ">
<div class="col-5 black-bg">

  <h1>Viewing rental details</h1>
<p><%= link_to "Return To Rentals List", rentals_path %></p>
<hr>

<% if @current_customer.id == @rental.customer_id %>

  <p><strong>Customer's Name: </strong><%= link_to @rental.customer.name, @rental.customer %></p>
  <p><strong>Movie: </strong><%= link_to @rental.movie.title, @rental.movie %></p>
  <p><strong>Rental Duration: </strong><%= @rental.rental_length %> days</p>

  <%= link_to "Rent a Movie", movies_path, class: "btn btn-danger float-right button-margin" %>
  <%= link_to "Edit Rental", edit_rental_path, class: "btn btn-danger float-right button-margin" %>
  <%= link_to "Delete Rental", rental_path(@rental), class: "btn btn-danger float-right button-margin", method: :delete %>

<% else %>

  <p><strong>Customer's Name: </strong><%= link_to @rental.customer.name, @rental.customer  %></p>
  <p><strong>Movie: </strong><%= link_to @rental.movie.title, @rental.movie %></p>
  <p><strong>Rental Duration: </strong><%= @rental.rental_length %> days</p>

<% end %>
</div>
</div>